env:
    browser: true
    es6: true
    jest: true
root: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2020
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
        '@typescript-eslint/explicit-function-return-type': on
        '@typescript-eslint/no-unused-vars': on
        'react/jsx-filename-extension':
            - 1
            - extensions:
                - ".ts"
                - ".tsx"
