env:
  browser: true
  jest: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:testing-library/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'testing-library'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
settings:
  'import/parsers':
    '@typescript-eslint/parser':
      - .tsx
      - .ts
  'import/extensions':
    - .ts
    - .tsx
  'import/resolver':
    node:
      extensions:
        - .ts
        - .tsx
